[package]
name = "day_2_threads"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ "atomics","hello_thread", "mutexes", "read_write_locks", "scoped_threads", "sum_the_vector", "thread_builder"]

